export const Top50Countries = [
    "Spain",
    "Argentina",
    "France",
    "England",
    "Brazil",
    "Portugal",
    "Netherlands",
    "Morocco",
    "Belgium",
    "Germany",
    "Croatia",
    "Senegal",
    "Italy",
    "Colombia",
    "USA",
    "Mexico",
    "Uruguay",
    "Switzerland",
    "Japan",
    "Iran",
    "Denmark",
    "South Korea",
    "Ecuador",
    "Austria",
    "Turkey",
    "Nigeria",
    "Australia",
    "Algeria",
    "Canada",
    "Ukraine",
    "Egypt",
    "Norway",
    "Panama",
    "Poland",
    "Wales",
    "Russia",
    "Ivory Coast",
    "Scotland",
    "Serbia",
    "Paraguay",
    "Hungary",
    "Sweden",
    "Czech Republic",
    "Slovakia",
    "Cameroon",
    "Greece",
    "Tunisia",
    "DR Congo",
    "Romania",
    "Venezuela",
    "Ireland"
];

export default Top50Countries;