export const Top50Countries = [
    { country: "Spain", flag: "🇪🇸" },
    { country: "Argentina", flag: "🇦🇷" },
    { country: "France", flag: "🇫🇷" },
    { country: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    { country: "Brazil", flag: "🇧🇷" },
    { country: "Portugal", flag: "🇵🇹" },
    { country: "Netherlands", flag: "🇳🇱" },
    { country: "Morocco", flag: "🇲🇦" },
    { country: "Belgium", flag: "🇧🇪" },
    { country: "Germany", flag: "🇩🇪" },
    { country: "Croatia", flag: "🇭🇷" },
    { country: "Senegal", flag: "🇸🇳" },
    { country: "Italy", flag: "🇮🇹" },
    { country: "Colombia", flag: "🇨🇴" },
    { country: "USA", flag: "🇺🇸" },
    { country: "Mexico", flag: "🇲🇽" },
    { country: "Uruguay", flag: "🇺🇾" },
    { country: "Switzerland", flag: "🇨🇭" },
    { country: "Japan", flag: "🇯🇵" },
    { country: "Iran", flag: "🇮🇷" },
    { country: "Denmark", flag: "🇩🇰" },
    { country: "South Korea", flag: "🇰🇷" },
    { country: "Ecuador", flag: "🇪🇨" },
    { country: "Austria", flag: "🇦🇹" },
    { country: "Turkey", flag: "🇹🇷" },
    { country: "Nigeria", flag: "🇳🇬" },
    { country: "Australia", flag: "🇦🇺" },
    { country: "Algeria", flag: "🇩🇿" },
    { country: "Canada", flag: "🇨🇦" },
    { country: "Ukraine", flag: "🇺🇦" },
    { country: "Egypt", flag: "🇪🇬" },
    { country: "Norway", flag: "🇳🇴" },
    { country: "Panama", flag: "🇵🇦" },
    { country: "Poland", flag: "🇵🇱" },
    { country: "Wales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
    { country: "Russia", flag: "🇷🇺" },
    { country: "Ivory Coast", flag: "🇨🇮" },
    { country: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
    { country: "Serbia", flag: "🇷🇸" },
    { country: "Paraguay", flag: "🇵🇾" },
    { country: "Hungary", flag: "🇭🇺" },
    { country: "Sweden", flag: "🇸🇪" },
    { country: "Czech Republic", flag: "🇨🇿" },
    { country: "Slovakia", flag: "🇸🇰" },
    { country: "Cameroon", flag: "🇨🇲" },
    { country: "Greece", flag: "🇬🇷" },
    { country: "Tunisia", flag: "🇹🇳" },
    { country: "DR Congo", flag: "🇨🇩" },
    { country: "Romania", flag: "🇷🇴" },
    { country: "Venezuela", flag: "🇻🇪" },
    { country: "Ireland", flag: "🇮🇪" }
];

export default Top50Countries;