export const Top50Countries = [
    { country: "Spain", flag: "🇪🇸", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Argentina", flag: "🇦🇷", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "France", flag: "🇫🇷", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "England", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Brazil", flag: "🇧🇷", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Portugal", flag: "🇵🇹", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Netherlands", flag: "🇳🇱", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Morocco", flag: "🇲🇦", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "Belgium", flag: "🇧🇪", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Germany", flag: "🇩🇪", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Croatia", flag: "🇭🇷", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Senegal", flag: "🇸🇳", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "Italy", flag: "🇮🇹", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Colombia", flag: "🇨🇴", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "USA", flag: "🇺🇸", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Mexico", flag: "🇲🇽", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Uruguay", flag: "🇺🇾", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Switzerland", flag: "🇨🇭", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Japan", flag: "🇯🇵", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] },
    { country: "Iran", flag: "🇮🇷", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] },
    { country: "Denmark", flag: "🇩🇰", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "South Korea", flag: "🇰🇷", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] },
    { country: "Ecuador", flag: "🇪🇨", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Austria", flag: "🇦🇹", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Turkey", flag: "🇹🇷", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Nigeria", flag: "🇳🇬", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "Australia", flag: "🇦🇺", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] },
    { country: "Algeria", flag: "🇩🇿", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "Canada", flag: "🇨🇦", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Ukraine", flag: "🇺🇦", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Egypt", flag: "🇪🇬", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "Norway", flag: "🇳🇴", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Panama", flag: "🇵🇦", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Poland", flag: "🇵🇱", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Wales", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Russia", flag: "🇷🇺", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Ivory Coast", flag: "🇨🇮", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "Scotland", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Serbia", flag: "🇷🇸", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Paraguay", flag: "🇵🇾", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Hungary", flag: "🇭🇺", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Sweden", flag: "🇸🇪", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Czech Republic", flag: "🇨🇿", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Slovakia", flag: "🇸🇰", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Cameroon", flag: "🇨🇲", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "Greece", flag: "🇬🇷", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Tunisia", flag: "🇹🇳", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "DR Congo", flag: "🇨🇩", tournaments: ["AFCON", "AfricaFriendly", "World Cup"] },
    { country: "Romania", flag: "🇷🇴", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Venezuela", flag: "🇻🇪", tournaments: ["Copa America", "American Friendly", "World Cup"] },
    { country: "Ireland", flag: "🇮🇪", tournaments: ["Euros", "Euros Friendly", "World Cup"] },
    { country: "Qatar", flag: "🇶🇦", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] },
    { country: "Saudi Arabia", flag: "🇸🇦", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] },
    { country: "China", flag: "🇨🇳", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] },
    { country: "UAE", flag: "🇦🇪", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] },
    { country: "Iraq", flag: "🇮🇶", tournaments: ["Other Tournament", "Other Friendly", "World Cup"] }
];

export default Top50Countries;